<?php

########################################################################
# Extension Manager/Repository config file for ext: "t3community"
#
# Auto generated by Extbase Kickstarter 2010-02-05
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 't3community',
	'description' => '',
	'category' => '',
	'author' => 'Gordon Brüggemann,Felix Krüger',
	'author_email' => 'gordon.brueggemann@tudock.de,felix.krueger@tudock.de',
	'author_company' => 'TUDOCK Pahlmann & Wolf GbR,TUDOCK Pahlmann & Wolf GbR',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>